### ISSUE TITLE
TODO: requirements

### ISSUE THREAD

**Issue by donggyu3728** [sweteam5/2019-1-SE-team5#1]
1. Save & Load
    

  - [ ] Save finally customized file with chrome sync
  - [ ] Load customized file before display the site
  - [ ] Show saved files on console (AFTERTHAT: show suggestion of customized files from server)

2. Undo
  - [ ] Undo change which is done just before

3. Selector
  - [ ] Escape selection state with ESC or click other location of webpage
  - [ ] Return to Selector after deletion of selected element

4. Other request
  - [ ] Change click&pause time to call console BEFORE release v1.0
